#!/usr/bin/env bash
# PreToolUse(Edit|Write|MultiEdit) guard — protects generated + secret files.
set -euo pipefail

path=$(jq -r '.tool_input.file_path // empty')
[ -z "$path" ] && exit 0

# Auto-generated build outputs — never hand-edit.
case "$path" in
  */dist/*|dist/*|*/build/*)
    echo "Blocked: this file is auto-generated (build output) — never edit it by hand." >&2
    exit 2
    ;;
esac

# Lockfile — regenerate via the package manager, never hand-edit.
case "$path" in
  *pnpm-lock.yaml)
    echo "Blocked: pnpm-lock.yaml is generated by pnpm — never edit it by hand." >&2
    exit 2
    ;;
esac

case "$path" in
  *.env|*.env.*)
    jq -n '{
      hookSpecificOutput: {
        hookEventName: "PreToolUse",
        permissionDecision: "ask",
        permissionDecisionReason: "Editing an env file — it may contain secrets. Confirm before writing."
      }
    }'
    exit 0
    ;;
esac

exit 0
